# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'rackup', '~> 2.3'
gem 'puma', '~> 6.0'
gem 'parallel', '~> 1.26'
gem 'ruby-progressbar', '~> 1.13'

group :test do
  gem 'rspec', '~> 3.13'
  gem 'rack-test', '~> 2.1'
end
