# frozen_string_literal: true

require 'dotenv/load'

MONGODB_API_KEY = ENV.fetch('MONGODB_API_KEY')
MONGODB_URI = ENV.fetch('MONGODB_URI')
MONGODB_DATABASE = ENV.fetch('MONGODB_DATABASE', 'frugal')
EMBEDDING_MODEL = "voyage-4-lite"
EMBEDDING_DIMENSIONS = 1024
VECTOR_SEARCH_LIMIT = 5
VECTOR_SEARCH_CANDIDATES = 100
SIMILARITY_THRESHOLD = 0.75
