import assert from "node:assert/strict";
import test from "node:test";
import type { ProxySnapshot } from "../app/types/dashboard";
import { buildSummaryCards } from "../app/utils/dashboard-summary-cards";

function createSnapshot(): ProxySnapshot {
  return {
    startedAt: "2026-03-20T12:00:00.000Z",
    queueDepth: 0,
    recentRequestLimit: 1000,
    totals: {
      activeRequests: 0,
      successfulRequests: 0,
      failedRequests: 0,
      cancelledRequests: 0,
      rejectedRequests: 0,
    },
    backends: [
      {
        id: "a",
        name: "A",
        baseUrl: "http://a",
        connector: "openai",
        enabled: true,
        healthy: true,
        maxConcurrency: 1,
        lastError: "",
        lastCheckedAt: "",
        activeRequests: 0,
        availableSlots: 1,
        totalRequests: 0,
        successfulRequests: 0,
        failedRequests: 0,
        cancelledRequests: 0,
        configuredModels: ["gpt-small"],
        discoveredModels: ["gpt-small"],
        discoveredModelDetails: [],
      },
      {
        id: "b",
        name: "B",
        baseUrl: "http://b",
        connector: "openai",
        enabled: true,
        healthy: false,
        maxConcurrency: 1,
        lastError: "",
        lastCheckedAt: "",
        activeRequests: 0,
        availableSlots: 1,
        totalRequests: 0,
        successfulRequests: 0,
        failedRequests: 0,
        cancelledRequests: 0,
        configuredModels: ["gpt-large"],
        discoveredModels: ["gpt-large"],
        discoveredModelDetails: [],
      },
    ],
    activeConnections: [
      {
        id: "req_active",
        phase: "streaming",
        method: "POST",
        path: "/v1/chat/completions",
        startedAt: "2026-03-20T12:00:00.000Z",
        elapsedMs: 1000,
        queueMs: 100,
        kind: "chat.completions",
        model: "gpt-small",
        backendId: "a",
        backendName: "A",
        clientStream: true,
        upstreamStream: true,
        statusCode: 200,
        effectiveCompletionTokenLimit: 128,
        completionTokens: 10,
        contentTokens: 10,
        reasoningTokens: 0,
        textTokens: 10,
        completionTokensPerSecond: 25,
        totalTokens: 10,
        metricsExact: true,
      },
      {
        id: "req_waiting",
        phase: "queued",
        method: "POST",
        path: "/v1/chat/completions",
        startedAt: "2026-03-20T12:00:01.000Z",
        elapsedMs: 500,
        queueMs: 0,
        kind: "chat.completions",
        model: "gpt-large",
        backendId: "",
        backendName: "",
        clientStream: true,
        upstreamStream: false,
        statusCode: undefined,
        effectiveCompletionTokenLimit: undefined,
        completionTokens: 0,
        contentTokens: 0,
        reasoningTokens: 0,
        textTokens: 0,
        completionTokensPerSecond: undefined,
        totalTokens: 0,
        metricsExact: true,
      },
    ],
    recentRequests: [
      {
        id: "req_success",
        time: "2026-03-20T12:00:00.000Z",
        method: "POST",
        path: "/v1/chat/completions",
        requestType: "stream",
        model: "gpt-small",
        backendId: "a",
        backendName: "A",
        outcome: "success",
        latencyMs: 1000,
        queuedMs: 100,
      },
      {
        id: "req_error",
        time: "2026-03-20T12:00:00.000Z",
        method: "POST",
        path: "/v1/chat/completions",
        requestType: "json",
        model: "gpt-large",
        backendId: "b",
        backendName: "B",
        outcome: "error",
        latencyMs: 2000,
        queuedMs: 0,
      },
      {
        id: "req_cancelled",
        time: "2026-03-20T12:00:00.000Z",
        method: "POST",
        path: "/v1/chat/completions",
        requestType: "stream",
        model: "gpt-large",
        backendId: "b",
        backendName: "B",
        outcome: "cancelled",
        latencyMs: 2000,
        queuedMs: 0,
      },
      {
        id: "req_rejected",
        time: "2026-03-20T12:00:00.000Z",
        method: "POST",
        path: "/v1/chat/completions",
        requestType: "json",
        model: "",
        backendId: "",
        backendName: "",
        outcome: "queued_timeout",
        latencyMs: 500,
        queuedMs: 0,
      },
    ],
  };
}

test("buildSummaryCards derives dashboard card counts and drilldowns", () => {
  const cards = buildSummaryCards(createSnapshot());

  assert.equal(cards.length, 4);
  assert.equal(cards[1]?.value, "1 / 2");
  assert.equal(cards[2]?.value, "1 - 1");
  assert.equal(cards[3]?.value, "1 / 1 / 1 / 1");
  assert.deepEqual(cards[3]?.segments?.map((segment) => segment.drilldown?.query?.outcome), [
    "success",
    "error",
    "cancelled",
    "rejected",
  ]);
});
