http:
  routers:
    dashboard-api:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: dashboard-api
      tls:
        certResolver: letsencrypt

    dashboard-web:
      rule: "Host(`srv1513085.hstgr.cloud`)"
      entryPoints:
        - websecure
      service: dashboard-web
      priority: 1
      tls:
        certResolver: letsencrypt

    llmproxy:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/llmproxy`)"
      entryPoints:
        - websecure
      service: llmproxy
      priority: 1
      tls:
        certResolver: letsencrypt

    victoria-api:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/victoria`)"
      entryPoints:
        - websecure
      service: victoria-traces
      middlewares:
        - strip-victoria-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    middleware-simple:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/middlewares/simple`)"
      entryPoints:
        - websecure
      service: middleware-simple
      middlewares:
        - strip-middleware-simple-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    middleware-onnx:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/middlewares/onnx`)"
      entryPoints:
        - websecure
      service: middleware-onnx
      middlewares:
        - strip-middleware-onnx-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    middleware-llm:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/middlewares/llm`)"
      entryPoints:
        - websecure
      service: middleware-llm
      middlewares:
        - strip-middleware-llm-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    middleware-vs:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/middlewares/vs`)"
      entryPoints:
        - websecure
      service: middleware-vs
      middlewares:
        - strip-middleware-vs-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    middleware-svc:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/middlewares/svc`)"
      entryPoints:
        - websecure
      service: middleware-svc
      middlewares:
        - strip-middleware-svc-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    middleware-oldschool:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/middlewares/oldschool`)"
      entryPoints:
        - websecure
      service: middleware-oldschool
      middlewares:
        - strip-middleware-oldschool-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    strip-victoria-prefix:
      stripPrefix:
        prefixes:
          - /victoria
    strip-middleware-simple-prefix:
      stripPrefix:
        prefixes:
          - /middlewares/simple
    strip-middleware-onnx-prefix:
      stripPrefix:
        prefixes:
          - /middlewares/onnx
    strip-middleware-llm-prefix:
      stripPrefix:
        prefixes:
          - /middlewares/llm
    strip-middleware-vs-prefix:
      stripPrefix:
        prefixes:
          - /middlewares/vs
    strip-middleware-svc-prefix:
      stripPrefix:
        prefixes:
          - /middlewares/svc
    strip-middleware-oldschool-prefix:
      stripPrefix:
        prefixes:
          - /middlewares/oldschool

  services:
    dashboard-api:
      loadBalancer:
        servers:
          - url: "http://dashboard-backend:8080"

    dashboard-web:
      loadBalancer:
        servers:
          - url: "http://dashboard-frontend:80"

    llmproxy:
      loadBalancer:
        servers:
          - url: "http://llmproxy:4100"

    victoria-traces:
      loadBalancer:
        servers:
          - url: "http://victoriatraces:10428"

    middleware-simple:
      loadBalancer:
        servers:
          - url: "http://middleware-simple:3000"

    middleware-onnx:
      loadBalancer:
        servers:
          - url: "http://middleware-onnx:3001"

    middleware-llm:
      loadBalancer:
        servers:
          - url: "http://middleware-llm:3002"

    middleware-vs:
      loadBalancer:
        servers:
          - url: "http://middleware-vs:3003"

    middleware-svc:
      loadBalancer:
        servers:
          - url: "http://middleware-svc:3004"

    middleware-oldschool:
      loadBalancer:
        servers:
          - url: "http://middleware-oldschool:3005"
