http:
  routers:
    dashboard-api:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/api`)"
      entryPoints:
        - websecure
      service: dashboard-api
      tls:
        certResolver: letsencrypt

    dashboard-web:
      rule: "Host(`srv1513085.hstgr.cloud`)"
      entryPoints:
        - websecure
      service: dashboard-web
      priority: 1
      tls:
        certResolver: letsencrypt

    jaeger-ui:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/jaeger`)"
      entryPoints:
        - websecure
      service: jaeger-ui
      priority: 10
      tls:
        certResolver: letsencrypt

    opensearch-api:
      rule: "Host(`srv1513085.hstgr.cloud`) && PathPrefix(`/opensearch`)"
      entryPoints:
        - websecure
      service: opensearch-api
      middlewares:
        - strip-opensearch-prefix
      priority: 10
      tls:
        certResolver: letsencrypt

    http-catchall:
      rule: "HostRegexp(`{host:.+}`)"
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      service: noop@internal

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    strip-opensearch-prefix:
      stripPrefix:
        prefixes:
          - /opensearch

  services:
    dashboard-api:
      loadBalancer:
        servers:
          - url: "http://dashboard-backend:8080"

    dashboard-web:
      loadBalancer:
        servers:
          - url: "http://dashboard-frontend:80"

    jaeger-ui:
      loadBalancer:
        servers:
          - url: "http://jaeger:16686"

    opensearch-api:
      loadBalancer:
        servers:
          - url: "http://opensearch:9200"
