services:
  middleware-simple:
    image: ghcr.io/jonasliebschner/frugal-ai-middleware-simple
    ports:
      - "3000:3000"

  # models need to be uploaded
  # middleware-onnx:
  #   image: ghcr.io/jonasliebschner/frugal-ai-middleware-onnx
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./models:/models
